version: 2.1

# use the node orb

orbs:
    node: circleci/node@4.7

# These three jobs are running exactly the same suite of tests, but on a different version of Node each time.

jobs:
    test-1:
        docker:
            - image: cimg/node:14.2
        resource_class: small
        steps:
            - checkout
            - node/install-packages:
                pkg-manager: yarn
            - run: 
                name: Make directory
                command: mkdir ~/junit1
            - run:
                name: Test application
                command: |
                    TEST=$(circleci tests glob "src/__tests__/*.js")
                    yarn test $TEST
            - run:
                name: Copy results
                command: cp junit.xml ~/junit1/
                when: always
            - store_test_results:
                path: ~/junit1

    test-2:
        docker:
            - image: cimg/node:15.11
        resource_class: small
        steps:
            - checkout
            - node/install-packages:
                pkg-manager: yarn
            - run: 
                name: Make directory
                command: mkdir ~/junit2
            - run:
                name: Test application
                command: |
                    TEST=$(circleci tests glob "src/__tests__/*.js")
                    yarn test $TEST
            - run:
                name: Copy results
                command: cp junit.xml ~/junit2/
                when: always
            - store_test_results:
                path: ~/junit2

    test-3:
        docker:
            - image: cimg/node:16.2
        resource_class: small
        steps:
            - checkout
            - node/install-packages:
                pkg-manager: yarn
            - run: 
                name: Make directory
                command: mkdir ~/junit3
            - run:
                name: Test application
                command: |
                    TEST=$(circleci tests glob "src/__tests__/*.js")
                    yarn test $TEST
            - run:
                name: Copy results
                command: cp junit.xml ~/junit3/
                when: always
            - store_test_results:
                path: ~/junit3

workflows:
    Testing:
      jobs:
        - test-1
        - test-2
        - test-3
