version: 2.1

# use the node orb

orbs:
    node: circleci/node@4.7

jobs:
    test:
      parameters:
        node-version:
          type: string
          default: "15.10.0"
      docker:
        - image: cimg/node:<< parameters.node-version >>
      resource_class: large
      steps:
        - checkout
        - node/install-packages:
            pkg-manager: yarn
        - run: 
            name: Make directory
            command: mkdir ~/junit-<< parameters.node-version >>
        - run:
            name: Test application
            command: |
                TEST=$(circleci tests glob "src/__tests__/*.js")
                yarn test $TEST
        - run:
            name: Copy results
            command: cp junit.xml ~/junit-<< parameters.node-version >>/
            when: always
        - store_test_results:
            path: ~/junit-<< parameters.node-version >>

workflows:
    Testing:
      jobs:
      - test:
          matrix:
            parameters:
              node-version: ["13.8", "14.2", "15.11"]
